version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes: 
        - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'        
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3333:3000
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    restart: always    

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
      
  kraken_designer:
    image: devopsfaith/krakendesigner:latest
    ports:
      - "8787:80"
  
  krakend_ce:
    image: devopsfaith/krakend:1.1.1
    volumes:
      - ./api-gw:/etc/krakend
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"      
    depends_on:
      - rabbitmq
      - fake_api
      - jaeger
      - prometheus
  
  jwt_revoke:
    build:
      context: ./jwt-revoker
    ports:
      - "9000:9000"
    depends_on:
      - krakend_ce

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  