# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: 'my-app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
         - targets: ['krakend_ce:5002']